from ship_management import db
# from ship_management.models import User,UserDescription,Department,DeptAssignment,Ship,ShipAssignment,ShipAttachment,OperatSection,NavigationArea,Summary,Summary2,ShipOwner,Concerned,ProCategory,TaskCategory,Project,Task,ProAttachment,ProAssignment,TaskAttachment,ProDescription,TakDescription,Role,UserHasRoles,Schedule
from ship_management.models import Ship
from datetime import datetime

# 日付データのサンプル
# date_str = '2021-09-10'  # 文字列形式の日付データ
# date_obj = datetime.strptime(date_str, '%Y-%m-%d')  # datetimeオブジェクトに変換


      # self.name = name
      # self.ex_name = ex_name  
      # self.yard = yard 
      # self.ship_no = ship_no 
      # self.delivered = delivered 
      # self.issued_Inscert = issued_Inscert 
      # self.expiry_date = expiry_date 
      # self.gross_tonn = gross_tonn 
      # self.operat_section_id = operat_section_id 
      # self.navigation_area_id = navigation_area_id

def shipsSeeder():
   ships01 = Ship( name= 'おふゆ' ,delivered=datetime.strptime( '2006-01-18', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2021-09-10', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-08-26', '%Y-%m-%d'), ex_name= '' , former_name= 'くまの丸' , yard = '金川' , ship_no = '548',  gross_tonn = '194' , operat_section_id = '4' , navigation_area_id= '1' )
   ships02 = Ship(  name= 'そうや' ,delivered=datetime.strptime('2009-11-25', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2020-07-01', '%Y-%m-%d'), expiry_date=datetime.strptime('2025-11-12', '%Y-%m-%d'), ex_name= '' , former_name= 'あきつ丸' , yard = '金川' , ship_no = '603', gross_tonn = '194' , operat_section_id = '4' , navigation_area_id= '1' )
   ships03 = Ship(  name= 'まみや' ,delivered=datetime.strptime('2016-05-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '' , yard = '金川' , ship_no = '686', gross_tonn = '192' , operat_section_id = '5' , navigation_area_id= '2' )
   ships04 = Ship(  name= 'つがる' ,delivered=datetime.strptime('2020-04-13', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2020-04-13', '%Y-%m-%d'), expiry_date=datetime.strptime('2025-04-12', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川', ship_no = '750' , gross_tonn = '194' , operat_section_id = '5' , navigation_area_id= '2' )
   ships05 = Ship(  name= '北野丸' ,delivered=datetime.strptime('1992-09-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '北野丸' , yard = '金川' , ship_no = '378', gross_tonn = '196' , operat_section_id = '6' , navigation_area_id= '2' )
   ships06 = Ship(  name= 'らいちょう' ,delivered=datetime.strptime('2002-11-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= 'たまの丸' , yard = '金川' , ship_no = '511', gross_tonn = '193' , operat_section_id = '7' , navigation_area_id= '2' )
   ships07 = Ship(  name= '三保丸' ,delivered=datetime.strptime('2010-11-22', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2023-04-28', '%Y-%m-%d'), expiry_date=datetime.strptime('2025-11-21', '%Y-%m-%d'), ex_name= '' , former_name= 'あわじ丸' , yard = '金川' , ship_no = '619', gross_tonn = '196' , operat_section_id = '7' , navigation_area_id= '2' )
   ships08 = Ship(  name= 'きよす' ,delivered=datetime.strptime('2021-08-06', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2021-08-12', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-08-11', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '762', gross_tonn = '198' , operat_section_id = '2' , navigation_area_id= '1' )
   ships09 = Ship(  name= 'かりや丸' ,delivered=datetime.strptime('2018-04-06', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2018-04-10', '%Y-%m-%d'), expiry_date=datetime.strptime('2024-04-09', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '707', gross_tonn = '197' , operat_section_id = '2' , navigation_area_id= '1' )
   ships10 = Ship(  name= 'あけの丸' ,delivered=datetime.strptime('2016-09-12', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2022-09-09', '%Y-%m-%d'), expiry_date=datetime.strptime('2028-09-13', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '690', gross_tonn = '196' , operat_section_id = '2' , navigation_area_id= '1' )
   ships11 = Ship(  name= 'あつみ丸' ,delivered=datetime.strptime('2014-02-05', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2018-11-20', '%Y-%m-%d'), expiry_date=datetime.strptime('2024-02-04', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '659', gross_tonn = '195' , operat_section_id = '2' , navigation_area_id= '2' )
   ships12 = Ship(  name= 'くまの' ,delivered=datetime.strptime('2023-03-22', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2023-03-23', '%Y-%m-%d'), expiry_date=datetime.strptime('2029-03-22', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '772', gross_tonn = '198' , operat_section_id = '2' , navigation_area_id= '1' )
   ships13 = Ship(  name= 'つしま丸' ,delivered=datetime.strptime('2020-06-12', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2020-06-15', '%Y-%m-%d'), expiry_date=datetime.strptime('2026-06-14', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '752', gross_tonn = '196' , operat_section_id = '2' , navigation_area_id= '1' )
   ships14 = Ship(  name= 'とらいとん' ,delivered=datetime.strptime('2008-07-15', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2023-05-19', '%Y-%m-%d'), expiry_date=datetime.strptime('2028-07-14', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '580', gross_tonn = '209' , operat_section_id = '1' , navigation_area_id= '2' )
   ships15 = Ship(  name= 'いしん' ,delivered=datetime.strptime('2019-02-25', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2019-02-25', '%Y-%m-%d'), expiry_date=datetime.strptime('2024-02-24', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '720', gross_tonn = '247' , operat_section_id = '1' , navigation_area_id= '3' )
   ships16 = Ship(  name= 'あさか丸' ,delivered=datetime.strptime('2012-09-14', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2022-08-01', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-09-13', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '645', gross_tonn = '233' , operat_section_id = '1' , navigation_area_id= '2' )
   ships17 = Ship(  name= '布引丸' ,delivered=datetime.strptime('2012-08-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '' , yard = '金川' , ship_no = '629', gross_tonn = '208' , operat_section_id = '3' , navigation_area_id= '1' )
   ships18 = Ship(  name= '港島丸' ,delivered=datetime.strptime('2016-02-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '' , yard = '金川' , ship_no = '680', gross_tonn = '194' , operat_section_id = '3' , navigation_area_id= '1' )
   ships19 = Ship(  name= 'シリウス' ,delivered=datetime.strptime('2007-10-31', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2022-11-08', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-10-30', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '569', gross_tonn = '117' , operat_section_id = '1' , navigation_area_id= '2' )
   ships20 = Ship(  name= 'ぎんが' ,delivered=datetime.strptime('2003-09-29', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2023-09-22', '%Y-%m-%d'), expiry_date=datetime.strptime('2028-09-28', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '358', gross_tonn = '78' , operat_section_id = '1' , navigation_area_id= '2' )
   ships21 = Ship(  name= 'みやま' ,delivered=datetime.strptime('2014-05-23', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2019-04-25', '%Y-%m-%d'), expiry_date=datetime.strptime('2024-05-22', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '660', gross_tonn = '235' , operat_section_id = '1' , navigation_area_id= '2' )
   ships22 = Ship(  name= 'たまの' ,delivered=datetime.strptime('2017-10-16', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2022-09-30', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-10-15', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '698', gross_tonn = '198' , operat_section_id = '1' , navigation_area_id= '2' )
   ships23 = Ship(  name= 'こつぢ丸' ,delivered=datetime.strptime('2015-02-09', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2019-11-25', '%Y-%m-%d'), expiry_date=datetime.strptime('2025-02-08', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '670', gross_tonn = '205' , operat_section_id = '1' , navigation_area_id= '2' )
   ships24 = Ship(  name= 'かさど丸' ,delivered=datetime.strptime('2004-03-26', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2019-01-16', '%Y-%m-%d'), expiry_date=datetime.strptime('2024-03-25', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '525', gross_tonn = '209' , operat_section_id = '1' , navigation_area_id= '2' )
   ships25 = Ship(  name= 'こまち丸' ,delivered=datetime.strptime('2011-07-25', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2021-05-19', '%Y-%m-%d'), expiry_date=datetime.strptime('2026-07-24', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '612', gross_tonn = '205' , operat_section_id = '1' , navigation_area_id= '2' )
   ships26 = Ship(  name= 'かいた丸' ,delivered=datetime.strptime('2018-06-22', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2023-05-30', '%Y-%m-%d'), expiry_date=datetime.strptime('2028-06-21', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = '金川' , ship_no = '713', gross_tonn = '196' , operat_section_id = '1' , navigation_area_id= '2' )
   ships27 = Ship(  name= 'おおつ丸' ,delivered=datetime.strptime('2015-07-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '' , yard = '金川' , ship_no = '677', gross_tonn = '196' , operat_section_id = '1' , navigation_area_id= '2' )
   ships28 = Ship(  name= '長門' ,delivered=datetime.strptime('2011-09-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '' , yard = '金川' , ship_no = '631', gross_tonn = '193' , operat_section_id = '9' , navigation_area_id= '2' )
   ships29 = Ship(  name= 'あすか' ,delivered=datetime.strptime('2000-04-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= 'みほ丸' , former_name= 'あかし丸' , yard = '金川' , ship_no = '483', gross_tonn = '195' , operat_section_id = '8' , navigation_area_id= '2' )
   ships30 = Ship(  name= '飛鳥丸' ,delivered=datetime.strptime('1991-07-01', '%Y-%m-%d'), issued_Inscert=None, expiry_date=None, ex_name= '' , former_name= '赤城丸' , yard = '金川' , ship_no = '361', gross_tonn = '196' , operat_section_id = '8' , navigation_area_id= '2' )
   ships31 = Ship(  name= 'てくのすⅡ' ,delivered=datetime.strptime('2017-03-15', '%Y-%m-%d'), issued_Inscert=datetime.strptime( '2022-03-01', '%Y-%m-%d'), expiry_date=datetime.strptime('2027-03-14', '%Y-%m-%d'), ex_name= '' , former_name= '' , yard = 'ダイゾー' , ship_no = '514', gross_tonn = '186' , operat_section_id = '10' , navigation_area_id= '2' )
   db.session.add_all([ships01,ships02,ships03,ships04,ships05,ships06,ships07,ships08,ships09,ships10,ships11,ships12,ships13,ships14,ships15,ships16,ships17,ships18,ships19,ships20,ships21,ships22,ships23,ships24,ships25,ships26,ships27,ships28,ships29,ships30,ships31])