"""empty message

Revision ID: e91d59626870
Revises: 
Create Date: 2024-06-14 14:59:02.506911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e91d59626870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dec_templates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dec_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doc_code', sa.VARCHAR(length=12), nullable=True),
    sa.Column('name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('file_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('file_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('file_category_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['file_category_id'], ['file_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
